### PR TITLE
Create an ASDF file for KONS-9

### PR DESCRIPTION
**Pull request by foretspaisibles**
The ASDF file makes it possible to QUICKLOAD KONS-9. There is also a package definition and a `development/run` script which loads the KONS-9 system and gives control to the RUN function.

I welcome your comments, suggestions, or questions!

### CODE REVIEW

**Comment by kaveh808** [comment]
Thank you! My first contributor.

How would I run from an emacs/slime setup using ASDF?

**Comment by foretspaisibles** [comment]
Here is my answer [from the reddit thread](https://www.reddit.com/r/Common_Lisp/comments/vcq8ky/comment/ict0sui/?utm_source=share&utm_medium=web2x&context=3)

Maybe one of the most common way is to rely on QUICKLISP to load the ASDF system which you are maybe already using:

~~~ lisp
(ql:quickload "kons-9")
;; (ql:quickload :kons-9)
~~~

QUICKLISP is a lisp software distribution system and a collection of ready-to-download-and-use Lisp software. It also can find your home-made software and load it. QUICKLISP is easy to install and use, you can book 1 hour to [skim over the instructions](https://www.quicklisp.org/beta/), setup your system and get familiar with basic operations. Most of the software listed on [Awesome CL](https://github.com/CodyReichert/awesome-cl#readme) is available through QUICKLISP and many more.

(Be sure to check options for QUICKLISP-QUICKSTART:INSTALL, especially the :PATH one.)

It is however possible to load the system with ASDF itself, as with
~~~ lisp
; SLIME 2.26.1
CL-USER> (asdf:find-system "kons-9")
#<ASDF/SYSTEM:SYSTEM "kons-9">
CL-USER> (asdf:load-system "kons-9")
~~~

Of course ASDF has to be told beforehand where it should look for systems, see the [manual](https://asdf.common-lisp.dev/asdf/Configuring-ASDF-to-find-your-systems.html).  It is easy enough to configure ASDF but using QUICKLISP is even easier.

**Comment by kaveh808** [comment]
Sorry to bother you, but I think my latest push broke something in the OpenGL bindings. If you have the time (no worries if you don't), could you please pull and run the first demo? I get:

Undefined function X86-DARWIN64::|glDisable| called with arguments (2896) .

**Comment by kaveh808** [comment]
It works if after asdf loads the system, I manually evaluate the opengl.lisp and shape.lisp files, in that order.

**Comment by kaveh808** [comment]
It is working now. Might have been a missing :initform ... 

I also added :serial t to the .asd file just in case.

Sorry for the bother.

**Comment by foretspaisibles** [comment]
Cool that it's working :-) I tried to start the software and I got a nice frame I could turn around but were not able to draw anything yet.  I'll give a look at that new version!

**Comment by kaveh808** [comment]
If you grab a newer version, you can type 'h' for key bindings. TAB brings
up a very work-in-progress menu...

**Pull request merged**
