### PR TITLE
README.md: Add blurb about API documentation 

### PR DESCRIPTION
**Pull request by lukego**
Add a link to the API reference to README.md with hopefully complete notes about how it is built and updated.

### CODE REVIEW

**Review by foretspaisibles — APPROVED** [review]
Thank you Luke, I tried the instructions by myself and only have a remark that I'll add by myself (Quicklisp without special ASDF configuration.)

That's great you have added useful pointers to specific points of PAX documentation!

**Comment by kayomarz** [comment]
@lukego, while following [building-the-documentation](https://github.com/kaveh808/kons-9#building-the-documentation) in the readme, I came across dependency errors on evaluating `(pax:update-asdf-system-html-docs kons-9::@api :kons-9)` in SLIME.

I resolved them by manually by doing:

```common-lisp
(ql:quickload :mgl-pax)
(ql:quickload :3bmd)
(ql:quickload :colorize)
```

Retrying `(pax:update-asdf-system-html-docs kons-9::@api :kons-9)` now works great and the documentation gets built.

I'm unable to figure out why quicklisp did not automatically load them. I'm relatively new to CL so maybe I'm missing something.

Starting with [kons-9.asd](https://github.com/kaveh808/kons-9/blob/main/kons-9.asd#L121), `kons-9/api-docs` includes (:kons-9 :mgl-pax) as its dependencies which looks right.

Next, if we look in [mgl-pax.asd](https://github.com/melisgl/mgl-pax/blob/f0fd1ab5af0cefed2edd98d5b2288270b2180b0a/mgl-pax.asd#L71), the above missing dependencies (:3bmd and :colorize) are declared but only under substem `mgl-pax/document`

At first I concluded that `kons-9/api-docs` should include `mgl-pax/document` as a dependency too but then this doesn't make sense because as a user of a library, we shouldn't need to worry about a libaries internal dependency tree. The latter gets affirmed here in [mgl-pax.asd#L14-L20](https://github.com/melisgl/mgl-pax/blob/master/mgl-pax.asd#L14-L20) which specifically mentions to use `mgl-pax` as a dependency and not subsystems such as `mgl-pax/document`

Is there something we need to add to our [kons-9.asd](https://github.com/kaveh808/kons-9/blob/main/kons-9.asd#L121)?

**Comment by lukego** [comment]
@kayomarz Good catch. I don't know the answer to this. I can guess^Wspeculate...

Should we use `QL:QUICKLOAD` instead of `REQUIRE` when building the docs? Maybe that's needed for the auto-loading magic to work in a Quicklisp environment?

Or otherwise if adding `mgl-pax/document` as a dependency solves the problem then maybe we should do that and separately file an issue on mgl-pax to see how we are mis-firing?

I confess that I don't use Quicklisp. I preinstall the dependencies locally before starting the image. This might mean that certain things like `REQUIRE` work on my setup but not others. Sorry for the inconvenience this causes.

**Comment by kayomarz** [comment]
@lukego I tried out your suggestions:

> Should we use QL:QUICKLOAD instead of REQUIRE when building the docs?

I tried `(ql:quickload :kons-9/api-docs)` instead of require but it results in the same error.

> Or otherwise if adding mgl-pax/document as a dependency solves the problem then...

The error does not occur after adding declaring `mgl-pax/document` as a dependecy like so:

```
(asdf:defsystem #:kons-9/api-docs
  :description "Kons-9 API: exported symbols and online documentation."
  :depends-on (:kons-9 :mgl-pax :mgl-pax/document)
  :components
  ((:file "src/api/api")))
```

Although we can get away with the above, as you suggested we should check with mgl-pax team.

I also did a [quick search on the  `mgl-pax` repository](https://github.com/search?q=repo%3Amelisgl%2Fmgl-pax%20update-asdf-system-html-docs&type=code). Seems like `autoload` is asked to load `mgl-pax/documentation` whenever `update-asdf-system-html-docs` is called but will autoload work with quicklisp to download a package?

**Pull request merged**
