### PR TITLE
Add automatic testing of pull requests using Github Actions

### PR DESCRIPTION
**Pull request by lukego**
This PR adds automatic pull-request testing using Github Actions.

This should *Just Work* on any branches containing these changes, including this one, and including other peoples' own Github forks.

The test is simple:

```
(asdf:load-op :kons-9)
(asdf:test-op :kons-9)
```

and failure is defined as `sbcl` exiting with non-zero status.

This addresses #112 should be sufficient to catch problems like #110.

On this branch the test environment (sbcl + dependencies) is installed via [Nix](https://nixos.org/). This gives a lot of control over dependencies e.g. ability to pin and patch them. I set this up according to the instructions at https://nix.dev/tutorials/continuous-integration-github-actions

An alternative would be to use e.g. `apt-get install sbcl` and Quicklisp for installation. I am happy to volunteer to maintain the Nix script but I have no objection if someone prefers to rework it in anther way and maintain that.

To run this test manually you can simply install Nix and then (on this branch) run:

```
kons-9$ nix-shell --run "sbcl --script test.lisp"
```

and it will automatically run using exactly the same sbcl and dependencies as the Github action. (I have only tested this on Linux/x86-64 but it might also work on Mac, I would be curious to know.)

See also [`act`](https://github.com/nektos/act) for a universal way of running Github Actions locally.

### CODE REVIEW

**Comment by lukego** [comment]
@kaveh808 I expected this test to run automatically but it's possible that the Action needs to be enabled somehow in the Github project settings.

It did work when I tested the PR against my own fork, see https://github.com/lukego/kons-9/actions for a log of the tests while debugging.

**Comment by mikelevins** [comment]
@lukego I'm dubious about depending on Nix or apt for testing on a project that is meant to be used on macOS and Windows. I don't use either Nix or apt on Windows or macOS, and don't wish to, but I do wish to be able to run tests against my changes before issuing pull requests for them. Can you assuage my misgivings?

**Comment by lukego** [comment]
I see these approaches as complementary.

Yes, we need tests that are comprehensive, easy for developers to run locally, and validate the project on multiple platforms. No, this branch does not provide any of those things. All it does is connect our bare-bones tests ("it compiles") with Continuous Integration on one arbitrary platform.

But there is value in simple things applied consistently. Merging this branch would mean that we catch problems like #110 that break the build before they are merged. It will also automatically pick up any future test cases that we add an expose to ASDF.

There is also a nice property of Github Actions: these tests will also run automatically even on experimental branches that we push to our private forks of kons-9. This means that we can see whether the tests pass before we choose to open a Pull Request. There is an `Actions` tab on the Github UI where we can observe this test activity, e.g. [here](https://github.com/lukego/kons-9/actions) for my kons-9 fork.

Of course we still need to develop strong test cases, make them easy for everyone to run, and get coverage of all major platforms. That will be a lot of work. But this seems to me like a small step in that direction that is not in conflict.

**Comment by mikelevins** [comment]
Great, @lukego, I think we're in complete agreement.

**Comment by lukego** [comment]
If this change is interesting then the next steps are:

1. Edit Github Project settings `Settings > Actions` to enable running the tests (somehow.)
2. If this branch seems reliable then merge onto `main`.

I can also close this PR if interest in these changes is only lukewarm.

**Comment by foretspaisibles** [comment]
My understanding is that it's interesting but also related to the outcome of the discussion in #112 (Smoke tests, automated testing) and this is why not much happened here. By the way you certainly have valuable advices and comments on the question of testing, maybe you are interested in re-joining that conversation?

**Comment by lukego** [comment]
@foretspaisibles This branch does not depend on the smoke tests. It uses `(require :kons-9)` as the initial test case i.e. it detects build failures. This would be valuable to enable now e.g. it would have caught the recent build-breaking merges.

Once there are more tests it can run those too and become more useful. The current version does run `(asdf:oos 'asdf:test-op :kons-9)` which does include any tests that are visible to ASDF (but I think that is a no-op for Kons-9 today.)

> By the way you certainly have valuable advices and comments on the question of testing, maybe you are interested in re-joining that conversation?

No, I have no strong feelings about which test framework to use. I am sure whatever people choose will not be my favorite one and I am fine with that. I don't think that "more cooks in the kitchen" will be productive to that discussion.

**Comment by foretspaisibles** [comment]
@lukego Thank you. I understand the two discussions are not dependent technically. My point just the two discussions are related as the features they provide to developers are related, so I would suggest not to interpret the lack of discussion, review or merge as a lack of interest and keep this PR open a bit longer.

**Comment by lukego** [comment]
Closing this because I think it will be more productive to develop my testing infrastructure outside of the main repo.

**Pull request closed without merging**
