### PR TITLE
doc/api: Draft API reference using MGL-PAX

### PR DESCRIPTION
**Pull request by lukego**
Today I made a start on an API reference manual for Kons-9.

New files on this branch:
- `doc/api.html` is the API reference in HTML (also preview at https://peach-amii-86.tiiny.site/)
- [`doc/api.md`](https://github.com/kaveh808/kons-9/blob/e1376c3acc92b83f4bf86999a0d0225b864688cc/doc/api.md) is the API reference in Github-friendly markdown format.
- [`src/api/api.lisp`](https://github.com/kaveh808/kons-9/blob/e1376c3acc92b83f4bf86999a0d0225b864688cc/src/api/api.lisp) is the source code based on [MGL-PAX](https://melisgl.github.io/mgl-pax-world/).
- `src/api/types.lisp` is bonus type declarations for SBCL to check on API calls.

#### Operational impact

- Nothing happens by default.
    - Just new files appearing in the repo.
    - No changes to existing code or coding style.
- Loading system `KONS-9/API-DOCS` will:
    - Load MGL-PAX as a dependency.
    - Export all API symbols from the KONS-9 package.
    - Add documentation strings to Kons-9 functions/variables/classes (also visible in SLIME/DESCRIBE/etc.)
 - Loading system `KONS-9/API-TYPES` will:
     - Use `DECLAIM` to put types onto API functions.
     - Cause SBCL to check these types when compiling new code that calls the Kons-9 API.
     - Probably break a couple of things due to misspecified types (bugs.)

#### TODO

- [ ] Get constructive feedback.
- [ ] Integrate MGL-PAX documentation generation with the build and CI.
    - I have done everything ad-hoc at the REPL for now.
- [ ] Make it complete.
- [ ] Make it correct.
- [ ] Make it good.
- [ ] Keep it up to date.

It's a start!

### CODE REVIEW

**Comment by foretspaisibles** [comment]
Oh it looks very cool @lukego, unluckily I only noticed the PR closing notification. :-D I'll look into that!

**Comment by kaveh808** [comment]
Hi @lukego 

I apologize for not having looked at this in a timely manner. If I understand correctly, it is a way of generating documentation for the system. As such, I think it could be useful, and if you are willing to do some initial examples, I'm happy to approve the PR if you resubmit.

Apologies again.

Kaveh

**Comment by lukego** [comment]
Good to know that you are open to upstreaming this kaveh. I think a first mergeable effort will need to automate the doc build and flesh out the content somewhat more.

**Comment by kaveh808** [comment]
What is the next step? Do you want to reopen the PR and I'll approve it? Then you can have a go at doing what needs to be done to generate docs?

Apologies for not having a better understanding of how MGL-PAX works.

**Comment by lukego** [comment]
@kaveh808 Maybe the next step is to define the workflow for building/updating the documentation and keeping it in sync with the code. I've asked for pointers over at https://github.com/melisgl/mgl-pax/issues/19. Once we have that then we could merge.

Most of the API is still undocumented for now but merging first and then adding the missing docs with a PR-and-merge workflow might work well for sanity checking and early editing new bits as they are written.

More from me soon once I understand the build/update/publish docs workflow better.

**Review by kaveh808 — APPROVED** [review]
Approving this. I'll let you guys take the lead on it.

**Pull request merged**
