### PR TITLE
Describe developer setup

### PR DESCRIPTION
**Pull request by foretspaisibles**
As we are quite a few people with different setups, the development/describe
provides a simple description of people's setups. Expand as required.

### CODE REVIEW

**Comment by kaveh808** [comment]
Nice idea. I'll merge this after Mikel has made the SBCL changes.

**Comment by kaveh808** [comment]
@foretspaisibles Would it be possible to extend this to Linux and Windows setups?

We can remove CCL, as we only support SBCL now.

How do you imagine it being used? We run the script and post the results in a discussion?

**Comment by foretspaisibles** [comment]
Yes the idea is for people to have an off-the-shelf “fingerprint” their system so that it is easy to discuss configuration and platform specific issues based on consistent information.

It's possible to expand to Linux (it should work as is on Linux) but for Windows, I'am not sure, it has been ages since I had my fingers on one. :-)

**Comment by kaveh808** [comment]
@foretspaisibles Could you remove CCL and make any changes you want for Linux? Then I'll merge the PR.

**Comment by foretspaisibles** [comment]
Sure!

**Comment by foretspaisibles** [comment]
So just to give an update, I got my hand on a Linux machine so that I can try my code there. I'll change a couple of things and push an updated version soon.

**Comment by kaveh808** [comment]
Excellent, thanks.

**Review by kaveh808 — APPROVED** [review]
Thanks!

**Pull request merged**
