### PR TITLE
Embryonic Vulkan backend

### PR DESCRIPTION
**Pull request by lukego**
This branch adds an embryonic Vulkan backend that currently only opens a blank window, waits one second, and then closes it.

> The longest journey begins with a single step.

This serves to (re)open a few questions:

- [ ] Do we want to use Vulkan?
- [ ] Is now the time to start?
- [ ] Is this a reasonable first step?
- [ ] What will be the second step?

Here is my unsolicited opinion on the topic based on no relevant experience whatsoever 😁

1. Yes, we want to use Vulkan. Sure, it will be harder and more complex, but Lisp hackers should not be learning legacy OpenGL APIs now in 2022. Better to bite the bullet and use a modern forwards-looking stack with more opportunities going forward.
2. Yes, now is the time to start using Vulkan. The OpenGL backend does not have the performance for medium-size scenes and it does not make sense to optimize that code (see above.) I for one need ~100K vertices minimum for my first steps to model printed circuit board fragments.
3. Yes, this is a reasonable first step. It basically just pulls in @awolven's CL-VULKAN dependency and checks that it works to "Hello world" level. (Sorry, I need to choose an `ACCEPT` restart during compilation on this branch for some reason.)
4. The next step would be to draw the origin in a Vulkan-idiomatic way. I suppose that would involve line-drawing using three vertex pairs loaded into buffers and then (third step) with a shader for adding the camera perspective... but I don't know if that is accurate?

I would welcome feedback from someone who knows what they are doing :laughing:

### CODE REVIEW

**Comment by omarbassam88** [comment]
I agree. I believe Vulkan is the more future proof solution. Also, most Real Time Game Engines nowadays are using Vulkan. So, I guess this can lead kons-9 to be a ful rendering solution and not having to export to Blender or other applications to render.

**Comment by JMC-design** [comment]
I've been looking at the vulkan bindings, and at least from my cursory inspections the 
https://github.com/JolifantoBambla/vk seem more complete and with better documentation. Some of it is nonsense documentation, but it's documented, and seems more lispy.
I'm not sure what that means about performance. I question why people use classes instead of structs when they don't need multiple inheritence or slot documentation?

**Comment by kaveh808** [comment]
Thanks for starting this discussion. I agree that Vulkan is probably the way forward.

Does Vulkan work with our glfw setup?

All of our 3D rendering code is currently in `opengl.lisp`, so that is what we need to reimplement in Vulkan as a first step.

And I will need to rework my experimental GUI code as well.

For now, I would like to keep the Vulkan development (which should only affect a small number of files) in its own branch, rather than merging it with main. I suspect the development will take some time, and I would rather do one major merge when Vulkan rendering is working at least at the level of the current OpenGL.

**Comment by awolven** [comment]
cl-vulkan uses its own trivial glfw implementation, which would have to be
replaced with cl-glfw3, but that would be simple and straightforward.  I
was hoping that GLOP might be available soon to avoid reworking that OS
window code twice.

**Comment by JMC-design** [comment]
Glop needs to add modifiers to all three OS's before more complex keybindings can be used, all of which is done by cffi.

**Comment by awolven** [comment]
Kaveh will have to make the choice to choose which vulkan binding to use,
but if he chooses not to use cl-vulkan then don't count on me to provide
support.  I have plenty of vulkan examples in my other repos to share with
you otherwise.

**Comment by kaveh808** [comment]
I had a look at the cl-vulkan and vk bindings. Let's go with cl-vulkan, as having @awolven on our team is a huge bonus. I also prefer the simpler interface.

I would like someone to step up and be our "Vulkan guy/gal" and manage this portion of the development.

**Comment by lukego** [comment]
I'll close this PR/branch since I haven't worked with Vulkan before and I wouldn't be "the Vulkan guy." My motivation here is only that the current OpenGL backend seems too performance-limited to get started with.

**Comment by kaveh808** [comment]
Thanks for starting this process, Luke. We definitely need to move to Vulkan.

**Comment by awolven** [comment]
Like I told Kaveh in a different email, I am currently busy restructuring
my layered vulkan code out of my REGEN repository to build what could be
considered "vulkan examples" but will really turn out to be a "vulkan
engine" with the ability to abstract the actual graphic language you're
using.  If I work hard I can probably have it ready by mid october, but as
I also mentioned to Kaveh, I'm juggling development on the text engine
(which is currently opengl 2.1 and 3.3), development of Hemlock, research
on user interface systems, and a part time job.

**Comment by lukego** [comment]
Thanks for the info! I will cool my jets since things seem to be under control already.

**Comment by awolven** [comment]
Another small issue with vulkan and glfw is, the last time I looked at it,
vulkan required glfw3.4 so glfw3.3.8 might not work.

**Pull request closed without merging**
